---
- name: Remove all apache, php, and nginx software
  when:
    - ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt:
    name:
      - apache2*
      - php*
      - nginx*
    state: absent
    purge: true
    autoremove: true
  become: true

---
- name: Remove all apache, php, and nginx software
  when:
    - ansible_facts['os_family'] == "RedHat"
  ansible.builtin.dnf:
    name:
      - apache*
      - php*
      - nginx*
    state: absent
    autoremove: true
  become: true
