---
# handlers file for snipe-it

- name: Restart NGINX
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Git dubious ownership # noqa command-instead-of-module
  ansible.builtin.shell: "git config --global --add safe.directory {{ snipe_install_dir }}"
  args:
    executable: /bin/bash
  become: true
